name: etheridentity_mvp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  url_launcher: ^6.2.5
  image_picker: ^1.0.4
  encrypt: ^5.0.1
  crypto: ^3.0.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.7
  file_picker: ^10.1.2
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

 
  assets:
    - assets/isim logo.png
    - assets/kılcal damar.png
    - assets/logo.png
    - assets/Untitled design.png


